### ISSUE TITLE
Refactor packages

### ISSUE THREAD

**Issue by v-ladynev** [v-ladynev/fluent-hibernate#13]
In the root package
```Java
H, HibernateRequest, HibernateHqlRequest, HibernateUpdate, 
IRequest, IStatelessRequest, Pagination, HibernateSessionFactory, HibernateObjectQuery 
```
The First proposal
```Java
com.github.fluent.hibernate
com.github.fluent.hibernate.core
com.github.fluent.hibernate.util
```
The Second proposal
```Java
com.github.fluent.hibernate
com.github.fluent.hibernate.lib
com.github.fluent.hibernate.lib.util
```
I think about splitting the root package on two or three ones

root
```Java
H, IRequest, IStatelessRequest
```
request(update)
```Java
HibernateRequest, HibernateHqlRequest, HibernateUpdate,  HibernateObjectQuery 
```
???
```Java
 Pagination
```
???
```Java
HibernateSessionFactory
```

**Comment by Levvy055** [comment]
first proposal is better and for HibernateSessionFactory make package factory and pagination just in Util

**Comment by v-ladynev** [comment]
"factory" package is an interesting proposal...the aim of util package is to hold internal utils such as InternalUtils class. Pagination is used for library external interface, for an example
```Java
List<User> users = H.<User>request(User.class) .pagination(new Pagination(0, 10)).list(); 
```

**Comment by v-ladynev** [comment]
May be com.github.fluent.hibernate.internal.util for InternalUtil.

**Comment by Levvy055** [comment]
can be
